[package]
name = "loggery-rs"
version = "0.1.0"
edition = "2021"
author = "Yash Saxena <yash.saxena.dev@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
once_cell = "1.17.1"
